### ISSUE TITLE
"Comments" are detected inside of Regex

### ISSUE THREAD

**Issue by andryshok** [tedious/JShrink#101]
Error in script after Minify when script contents has some code. For example 

return /^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(url);      minifed by  return /^([a-z][a-z\d\+\-\.]*:)?\/\};   

script minifed has errors
file Axios.js -  https://github.com/axios/axios

**Comment by tedivm** [comment]
This should be resolved in the latest version.
