### ISSUE TITLE
Regex Detection Failure

### ISSUE THREAD

**Issue by furkanmustafa** [tedious/JShrink#13]
(rev:b3d0a82) Cannot detect this regex and fails with 'Stray Regex Pattern' error.

``` javascript
        return /\?/ .test( url ) ? "&" : "?";
```
- This regex cannot get detected on line 233 because it doesn't have wrapping quotes.
- And it gets detected on line 248, but it catches the ending of regex, because it has question mark before getting closed. saveRegex() gets called (after the end of regex)
- So, saveRegex() function goes until the end of line and fails.

**Comment by eisberg** [comment]
Hi, 
problem in regexp in HighCharts Library (4.0.4, highstock.js):

Test code:

    $jsCode = '{dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");}';
    $s =\JShrink\Minifier::minify($jsCode );
        var_dump($jsCode);
        var_dump($s); //JS Error -  Uncaught SyntaxError: Invalid regular expression: /(NaN|{2}|^$)/: Nothing to repeat

Output:

string(90) "{dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");}"
string(89) "{dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN|{2}|^$)/.test(a)&&(a="M 0 0");}"

**Comment by tedivm** [comment]
@furkanmustafa you still planning on giving a fix a try?
