### ISSUE TITLE
Rewrite name of functions and variables

### ISSUE THREAD

**Issue by stefanosilvestrinimia** [tedious/JShrink#130]
Hi,
is there a way to rewrite name of functions and variables automatically ? 

for eg:

function setPriceCart() { ... }

could be renamed

function b() { ... }

thank you @tedivm

**Comment by tedivm** [comment]
This would require a lot more effort to do properly, as there would need to be proper tokenization/parsing to understand scope and deal with things properly. It would be a complete rearchitecture, and honestly if that's what you need there are already better tools out there for it (just not in php).
