### ISSUE TITLE
wanna implement code-obfuscation feature like UglifyJS

### ISSUE THREAD

**Issue by michitoshiYano** [tedious/JShrink#138]
I'm using JSrink to compress javascript code on server side.
I wish there was an optional feature code-obfuscation feature like [UglifyJS](https://github.com/mishoo/UglifyJS).
Can we implement the feature?(I can contribute for this.)

**Comment by tedivm** [comment]
JShrink ties to be minimalistic- it doesn't rewrite code, it just parses and removes whitespace. Obfuscation would require a very heavy rewrite.

**Comment by michitoshiYano** [comment]
thanks for checking this issue. I understood the background.
