### ISSUE TITLE
Newlines after //@cc_on comments are removed

### ISSUE THREAD

**Issue by mrclay** [tedious/JShrink#37]
This may be a corner case but JSMin handles it so I figured I'd document it.

Input:

``` js
//@cc_on/*
statement;
//@cc_on*/
```

So basically in IE6 this should cause the statement to be seen as commented out. But JShrink moves the statement into the comment for all browsers:

``` js
//@cc_on/*statement;
//@cc_on*/
```

**Comment by lbarulski** [comment]
+1

**Comment by gellu** [comment]
+1

**Comment by 10n** [comment]
+1

**Comment by diego3** [comment]
+1

**Comment by benjamw** [comment]
I'm having similar issues with things like `//@todo ...`.

**Comment by tedivm** [comment]
Closing this as IE6 is super dead.
