### ISSUE TITLE
Detail with comments

### ISSUE THREAD

**Issue by ilichmx** [tedious/JShrink#40]
Hello Good evening, I was checking your library which I think is very good option, but when I was testing it on a project I saw something that caught my attention, other than marking me error code javascript.

So I explain the situation well so you can understand the details.

When I schedule sometimes javascript code sometimes under certain lines with `/**/` to highlight that part I should check then sometimes I take sometimes not remove.

In a snippet so is the original.

``` javascript
    html+= this.header();
    html+= this.cabeceras();

    /**/
    var prevmes = this.fecha.mesPrevio();           
    var previo  = year;

    if(prevmes == 11){previo--;}

    previo  = new Date(previo, prevmes, 1);
    dias    = previo.mesDias();
    previo  = previo.mesDias() - (inicio - 1);
    /**/

    html+= '    <div class="row">';
    for(var a = previo; a <= dias; a++){
        html+= '<div class="cell noActivo"><div><div><span>'+ a +'</span></div></div></div>';
    }
```

Now when I compile your library skips the code that is between `/**/` and I compiled this way.

``` javascript
html+=this.header();html+=this.cabeceras();html+=' <div class="row">';for(var a=previo;a<=dias;a++){html+='  <div class="cell noActivo"><div><div><span>'+a+'</span></div></div></div>';}
```

As you can see I removed the code that is `/**/`[CODE]`/**/` Now if I delete the `/**/` I compile it in a good way.

**Comment by nickolasgregory** [comment]
Hi.
Unfortunately this fix broke my style of coding - using ```/**/``` to disable blocks of code by only adding/removing a single "/"

```javascript
/**
alert('A BLOCK OF COMMENTED OUT CODE');
/**/

/**/
alert('A BLOCK OF RUNNING CODE');
/**/
```
Gives
```
Uncaught exception 'RuntimeException' with message 'Unclosed multiline comment at position: 137' in JShrink\Minifier.php:398
```

Just thought I'd let you know.
Great lib by the way, I'd like to see it included here -> https://thephpleague.com/ :)
