### ISSUE TITLE
Unclosed string at position on regEx

### ISSUE THREAD

**Issue by OlofT** [tedious/JShrink#42]
It dies with: Uncaught exception 'RuntimeException' with message 'Unclosed string at position: 59'

given this string:
"var regEx = /[a-z0-9!#$%&'_+/=?^_`{|}~-]+(?:.[a-z0-9!#$%&'_+/=?^_`{|}~-]+)_@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.)+(?:[A-Z]_)\b/;"

EDIT:
The regEx is wrong, and shouldn't be like this. The start is  /[a-z0-9!#$%&'+/ which normally completes a regex. The question is, I guess, whether JSShrink should still die or not.

**Comment by sunel** [comment]
Same Here 
we have ``` /[\(\)@~`!#$%\^&*+=\-\[\]\\';,/{}|\\":<>\? ]/g.test(val) ``` as we have ``` " ``` in the code this lib is throwing error

**Comment by jdreesen** [comment]
Having the same problem with this regex: `/^(?:([^:/?#]+):)?(?:\/\/([^/?#]*))?([^?#]*)(?:\?([^#]*))?(?:#(.*))?/`
It's a valid JS regex but JShrink fails when the `/` at positions 10 and 29 are not explicitely escaped with `\/`.

**Comment by kirillkorovkin** [comment]
Possible solution:

![fix](https://user-images.githubusercontent.com/12132554/28524747-10e418c6-7082-11e7-970d-aa76f16b26fa.png)
