### ISSUE TITLE
Fails when re-compressing twitter's widgets.js

### ISSUE THREAD

**Issue by mikeytown2** [tedious/JShrink#46]
You can test it out with this: http://platform.twitter.com/widgets.js

**Comment by aufa** [comment]
@mikeytown2 this like from method [getReal()](https://github.com/tedious/JShrink/blob/master/src/JShrink/Minifier.php#L302) 

that call [processMultiLineComments()](https://github.com/tedious/JShrink/blob/master/src/JShrink/Minifier.php#L359)

if on getReal() method you change with : 
 ```php
$startIndex_position = $this->index_position;
return $this->getChar();
```
it will be working properly , but you must need to replace comments manually
