### ISSUE TITLE
ErrorException in Minifier.php line 476: Unclosed string at position

### ISSUE THREAD

**Issue by ghost** [tedious/JShrink#49]
Minifier should detect if a file is already minified and just return it without minifying it a second time. Processing an already minified js file sometimes leads to a:

ErrorException in Minifier.php line 476: Unclosed string at position

The error is thrown in vendor/tedivm/jshrink/src/JShrink/Minifier.php around line 471:

```
        // New lines in strings without line delimiters are bad- actual
        // new lines will be represented by the string \n and not the actual
        // character, so those will be treated just fine using the switch
        // block below.
        case "\n":
            throw new \RuntimeException('Unclosed string at position: ' . $startpos );
            break;
```

Any ideas how this could be mitigated on JShrink side or is this something which should be checked before calling minify()?

**Comment by raicabogdan** [comment]
Just hit this one right now, have you had any luck mitigating this particular issue?

Thank you.

**Comment by particleflux** [comment]
Same problem, with a minifed moment js ( https://raw.githubusercontent.com/moment/moment/2.12.0/min/moment-with-locales.min.js ).

**Comment by Webkadabra** [comment]
I've encountered  same error, but I've found that it's not due to some JS file - I get this error when SERVER HTTP AUTHENTICATION is requred (e.g. with `htpasswd`).
If I saved your day - star my project "Brainfock" please :+1:

**Comment by alexdd55** [comment]
when i remove moment.min.js it works fine
