### ISSUE TITLE
Not clear statement in usage in readme file

### ISSUE THREAD

**Issue by Corsari** [tedious/JShrink#52]
Hello
kindly
in the usage you state

```
<?php
include('vendor/autoload.php');

// Basic (default) usage.
$minifiedCode = \JShrink\Minifier::minify($js);

// Disable YUI style comment preservation.
$minifiedCode = \JShrink\Minifier::minify($js, array('flaggedComments' => false));
```

where is the file autoload.php ?

Thank you

**Comment by duncan3dc** [comment]
Hi @Corsari, you need to use [Composer](https://getcomposer.org/doc/01-basic-usage.md) to install this package, then when you run `composer` it will create `autoload.php` for you
