### ISSUE TITLE
static string concatenation

### ISSUE THREAD

**Issue by the-liquid-metal** [tedious/JShrink#55]
also statement like this: 

`template = '' +`
`'<div class="row">' +`
`'<h1>{{TITLE}}</h1>' +`
`'</div>' +`
`'<div class="row">' +`
`'<div class="alert alert-warning" role="alert">{{RESPONSE_TEXT}}</div>' +`
`'</div>';`

into

`template = '<div class="row"><h1>{{TITLE}}</h1></div><div class="row"><div class="alert alert-warning" role="alert">{{RESPONSE_TEXT}}</div></div>';`

**Comment by tedivm** [comment]
After a lot of thought I've decided that jshrink isn't going to take on this type of task- it removes whitespace, but moving into actual rewriting of code raises complexity and reduces performance.
