### ISSUE TITLE
Comment parsed as regex in list

### ISSUE THREAD

**Issue by qurben** [tedious/JShrink#57]
The following js snippet causes the minifier to fail:

```javascript
var list = [
	1,
	2,
	/***//**
	 */
	3,
	4
];
```

The following message is returned

```
Fatal error:  Uncaught exception 'RuntimeException' with message 'Unclosed regex pattern at position: 467212' in vendor\tedivm\jshrink\src\JShrink\Minifier.php:525
Stack trace:
#0 vendor\tedivm\jshrink\src\JShrink\Minifier.php(240): JShrink\Minifier->saveRegex()
#1 vendor\tedivm\jshrink\src\JShrink\Minifier.php(144): JShrink\Minifier->loop()
#2 vendor\tedivm\jshrink\src\JShrink\Minifier.php(110): JShrink\Minifier->minifyDirectToOutput('\n\n/* XXXXXXXXXX...', Array)
#3 script.php(89): JShrink\Minifier::minify('\n\n/* XXXXXXXXXX...')
#4 script.php(29): js_out()
#5 {main}
  thrown in vendor\tedivm\jshrink\src\JShrink\Minifier.php on line 525
```

**Comment by qurben** [comment]
`getReal` only processes one comment at a time, if the comment is a multiline comment the next character can be a `/`, if the previous character was a `,`, `saveRegex` is kicked off.

`getReal` should be able to process multiple comments or return an empty string/space and decrement the position with one when it detects a comment directly after the multiline comment.

**Comment by qurben** [comment]
Note that this happens any time there are (at least) two multiline comments directly after each other, where the second one has a `\n` in it and where the first one has one of `(,=:[!&|?` before it (excluding whitespace).

A lib I use has some documentation in this form:
```javascript
...
},

/**
 * Get the text for a button
 * @param  {int|string} node Button index
 * @return {string} Button text
 *//**
 * Set the text for a button
 * @param  {int|string|function} node Button index
 * @param  {string} label Text
 * @return {Buttons} Self for chaining
 */
text: function (...
```

**Comment by onassar** [comment]
Still happening for me; downloaded latest release, but no luck :(
