### ISSUE TITLE
"Unclosed multiline comment" using /* ... /**/

### ISSUE THREAD

**Issue by anakonda3000** [tedious/JShrink#67]
Hi

The minifier thows an error when I use following multiline comment:

`var d = 1;
/*
  test comment
/**/
var d = 2;`

This is a valid comment but not correctly handled by the shrinker.

BR

**Comment by Pangamma** [comment]
I'm also noticing this as well.
/* SOME STUFF HERE
* WILL
* FAIL */

**Comment by benjamw** [comment]
This is due to `$js = str_replace('/**/', '', $js);` in the `initialize` function.

Not even sure why that replacement is in there. It will get handled by the comment parser.

**Comment by tedivm** [comment]
Thanks for the issue! I've added the example into the test suite, and it appears that it was resolved in the refactor that removed the `str_replace` code.
