### ISSUE TITLE
Error when using string literals inside of template literals

### ISSUE THREAD

**Issue by atomicptr** [tedious/JShrink#69]
If you try to use a string literal (**'** or **"**) within a template literal ( Backticks / https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals ) it throws an error.

Example:

```php
<?php
echo \JShrink\Minifier::minify("let x = `I'm here`;");
```

**Comment by Igloczek** [comment]
Looks like there is just no ES6 support and also project looks like dead thing :/
Related issue - #66

**Comment by tedivm** [comment]
The project isn't dead, I'm just not actively working on it. I do review and merge pull requests.
