### ISSUE TITLE
Seems to work fine on php 5.5, why require 5.6?

### ISSUE THREAD

**Issue by patientairplane** [tedious/JShrink#74]
Regarding this change:

https://github.com/tedious/JShrink/commit/11054401345c5f2f0ae9528ecc6e289795df15f0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by tedivm** [comment]
[This is why](http://php.net/supported-versions.php). PHP5.5 has been dead for almost two years now.
