### ISSUE TITLE
update list of supported PHP versions

### ISSUE THREAD

**Issue by Findus23** [tedious/JShrink#80]
Hi,

Many thanks for fixing the 7.3 warning. 
I just tried updating the library, but composer only installs `1.1`.

I think this is because you mention here that the library is not compatible with 7.1+:
https://github.com/tedious/JShrink/blob/21254058dc3ce6aba6bef458cff4bfa25cf8b198/composer.json#L15

It would be really great if you could update this to 5.6-7.3 and release a new version.

**Comment by Findus23** [comment]
Okay, I take everything back and claim the opposite :slightly_smiling_face: 
I totally mixed up 5.5 and 5.6 and the application has a 
```json
        "platform": {
            "php": "5.5.9"
        }
```
requirement.

Sorry for the confusion.

**Comment by tedivm** [comment]
No worries- glad we got this figured out!
