### ISSUE TITLE
1.3.2 breaks when trying to convert certain local files

### ISSUE THREAD

**Issue by clivewalkden** [tedious/JShrink#85]
I've come across an issue with the latest update (1.3.2) with moment.js including locales version 2.17.1. In your version 1.3.1 there is no issue. The issue came to light during a Magento 2 deployment (for which this is a dependency). 

The following string code causes the issue: `/-MMM-/` from the following
```
monthsShort: {
    return /-MMM-/.test(b) ? Mg[a.month()] : Lg[a.month()]
}
```
```
PHP Fatal error:  Uncaught RuntimeException: Unclosed regex pattern at position: 111357 in E:\dir\git\vendor\tedivm\jshrink\src\JShrink\Minifier.php:530
Stack trace:
#0 E:\dir\git\vendor\tedivm\jshrink\src\JShrink\Minifier.php(247): JShrink\Minifier->saveRegex()
#1 E:\dir\git\vendor\tedivm\jshrink\src\JShrink\Minifier.php(147): JShrink\Minifier->loop()
#2 E:\dir\git\vendor\tedivm\jshrink\src\JShrink\Minifier.php(115): JShrink\Minifier->minifyDirectToOutput('!function (a, b...', Array)
#3 E:\dir\git\test.php(6): JShrink\Minifier::minify('!function (a, b...')
#4 {main}
  thrown in E:\dir\git\vendor\tedivm\jshrink\src\JShrink\Minifier.php on line 530
```

**Comment by Userr017** [comment]
Here is also more information about this issue https://github.com/magento/magento2/issues/23410

**Comment by MarianMates** [comment]
Also crashing for vendor/magento/module-swagger/view/frontend/web/swagger-ui/js/swagger-ui-bundle.js
Prereq : 
    Deploy mode : production (cannot reproduce on development)
    Js/minify_files : true

**Comment by tedivm** [comment]
I've put out a new release which removes the regression, and will add more test cases before reapplying that bug fix.
