### ISSUE TITLE
proper string concatenation

### ISSUE THREAD

**Issue by columbian-chris** [tedious/JShrink#88]
JShrink takes this:

```js
var hello = 'hi ' + 'there';
```

and turns it into:

```js
var hello='hi '+'there';
```

It is unnecessary in javascript minification to join strings with concatenation operators (plus signs). Proper minification would produce:

```js
var hello='hi there';
```

**Comment by tedivm** [comment]
JShrink is designed to be a quick inline minifier that sacrificed perfect minification in favor of performance. It only removes whitepsace, it does not make any attempts to rewrite code- doing so would be much more complex, and honestly there's better tools out there for that (which can be run to create static bundles, where the performance isn't as much of a concern).
