### ISSUE TITLE
"strpos()" including deprecated String

### ISSUE THREAD

**Issue by Darkice78** [tedious/JShrink#89]
When i turn my server to PHP7.3 i get the following error:
<b>Deprecated</b>:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in <b>.../minifier.php</b> on line <b>184</b><br />

**Comment by webrectoversocreationbe** [comment]
that's why i'm here...  to check if a new release is done, or explain what i've done to resolve this error :
`if ((string)$this->b!='' && strpos('(-+[@', (string)$this->b) !== false) {`

**Comment by TimGS** [comment]
+1. Running PHP 7.3 on Debian 10.

**Comment by tedivm** [comment]
Please reopen with an example code that will trigger this. That said I think the existing behavior with php8 should work without warning or error.
