### ISSUE TITLE
Error on php 7.4.1

### ISSUE THREAD

**Issue by sashabeep** [tedious/JShrink#92]
```
Error : "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```
File | /home/...../Minifier.php
-- | --
Line | 227
Source | continue;

Changed to ```continue 2```
```
Error : "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"?
```
Changed to ```continue 3``` But i'm unclear than is finally resolves the error... ?

**Comment by tedivm** [comment]
PHP7 is no longer supported.
